# Generated by Django 2.2.8 on 2019-12-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=64)),
                ('banner_details', models.TextField()),
                ('detail_heading', models.CharField(max_length=64)),
                ('details', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/webpic/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=64)),
                ('image', models.ImageField(default='profile/default.png', null=True, upload_to='profile/')),
                ('producttype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='desktop.ProductType')),
            ],
        ),
    ]
