# Generated by Django 2.2.8 on 2019-12-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=64)),
                ('image', models.ImageField(default='profile/default.png', null=True, upload_to='profile/')),
            ],
        ),
    ]
