# Generated by Django 2.2.8 on 2019-12-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='producttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='desktop.ProductType'),
        ),
    ]
