# Generated by Django 2.2.8 on 2019-12-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0002_auto_20191211_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('history_title', models.CharField(max_length=64)),
                ('history_description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='aboutus')),
            ],
        ),
    ]
