# Generated by Django 2.2.8 on 2019-12-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0002_auto_20191210_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
