# Generated by Django 2.2.8 on 2019-12-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='map',
            field=models.TextField(null=True),
        ),
    ]
